
import { Surah } from './types';

export const SURAH_LIST: Surah[] = [
  { number: 1, name: "Al-Fatihah", arabic: "الفاتحة", meaning: "Pembukaan", verses: 7, type: "Makkiyah", juz: 1 },
  { number: 2, name: "Al-Baqarah", arabic: "البقرة", meaning: "Sapi Betina", verses: 286, type: "Madaniyah", juz: 1 },
  { number: 3, name: "Ali 'Imran", arabic: "آل عمران", meaning: "Keluarga Imran", verses: 200, type: "Madaniyah", juz: 3 },
  { number: 4, name: "An-Nisa'", arabic: "النساء", meaning: "Wanita", verses: 176, type: "Madaniyah", juz: 4 },
  { number: 5, name: "Al-Ma'idah", arabic: "المائدة", meaning: "Hidangan", verses: 120, type: "Madaniyah", juz: 6 },
  { number: 6, name: "Al-An'am", arabic: "الأنعام", meaning: "Binatang Ternak", verses: 165, type: "Makkiyah", juz: 7 },
  { number: 7, name: "Al-A'raf", arabic: "الأعراف", meaning: "Tempat Tertinggi", verses: 206, type: "Makkiyah", juz: 8 },
  { number: 8, name: "Al-Anfal", arabic: "الأنفال", meaning: "Rampasan Perang", verses: 75, type: "Madaniyah", juz: 9 },
  { number: 9, name: "At-Taubah", arabic: "التوبة", meaning: "Pengampunan", verses: 129, type: "Madaniyah", juz: 10 },
  { number: 10, name: "Yunus", arabic: "يونس", meaning: "Nabi Yunus", verses: 109, type: "Makkiyah", juz: 11 },
  { number: 11, name: "Hud", arabic: "هود", meaning: "Nabi Hud", verses: 123, type: "Makkiyah", juz: 11 },
  { number: 12, name: "Yusuf", arabic: "يوسف", meaning: "Nabi Yusuf", verses: 111, type: "Makkiyah", juz: 12 },
  { number: 13, name: "Ar-Ra'd", arabic: "الرعد", meaning: "Guruh", verses: 43, type: "Madaniyah", juz: 13 },
  { number: 14, name: "Ibrahim", arabic: "إبراهيم", meaning: "Nabi Ibrahim", verses: 52, type: "Makkiyah", juz: 13 },
  { number: 15, name: "Al-Hijr", arabic: "الحجر", meaning: "Batu Gunung", verses: 99, type: "Makkiyah", juz: 14 },
  { number: 16, name: "An-Nahl", arabic: "النحل", meaning: "Lebah", verses: 128, type: "Makkiyah", juz: 14 },
  { number: 17, name: "Al-Isra'", arabic: "الإسراء", meaning: "Perjalanan Malam", verses: 111, type: "Makkiyah", juz: 15 },
  { number: 18, name: "Al-Kahf", arabic: "الكهف", meaning: "Gua", verses: 110, type: "Makkiyah", juz: 15 },
  { number: 19, name: "Maryam", arabic: "مريم", meaning: "Maryam", verses: 98, type: "Makkiyah", juz: 16 },
  { number: 20, name: "Taha", arabic: "طه", meaning: "Taha", verses: 135, type: "Makkiyah", juz: 16 },
  { number: 21, name: "Al-Anbiya'", arabic: "الأنبياء", meaning: "Para Nabi", verses: 112, type: "Makkiyah", juz: 17 },
  { number: 22, name: "Al-Hajj", arabic: "الحج", meaning: "Haji", verses: 78, type: "Madaniyah", juz: 17 },
  { number: 23, name: "Al-Mu'minun", arabic: "المؤمنون", meaning: "Orang Beriman", verses: 118, type: "Makkiyah", juz: 18 },
  { number: 24, name: "An-Nur", arabic: "النور", meaning: "Cahaya", verses: 64, type: "Madaniyah", juz: 18 },
  { number: 25, name: "Al-Furqan", arabic: "الفرقان", meaning: "Pembeda", verses: 77, type: "Makkiyah", juz: 18 },
  { number: 26, name: "Asy-Syu'ara'", arabic: "الشعراء", meaning: "Para Penyair", verses: 227, type: "Makkiyah", juz: 19 },
  { number: 27, name: "An-Naml", arabic: "النمل", meaning: "Semut", verses: 93, type: "Makkiyah", juz: 19 },
  { number: 28, name: "Al-Qasas", arabic: "القصص", meaning: "Kisah-kisah", verses: 88, type: "Makkiyah", juz: 20 },
  { number: 29, name: "Al-'Ankabut", arabic: "العنكبوت", meaning: "Laba-laba", verses: 69, type: "Makkiyah", juz: 20 },
  { number: 30, name: "Ar-Rum", arabic: "الروم", meaning: "Romawi", verses: 60, type: "Makkiyah", juz: 21 },
  { number: 31, name: "Luqman", arabic: "لقمان", meaning: "Luqman", verses: 34, type: "Makkiyah", juz: 21 },
  { number: 32, name: "As-Sajdah", arabic: "السجدة", meaning: "Sujud", verses: 30, type: "Makkiyah", juz: 21 },
  { number: 33, name: "Al-Ahzab", arabic: "الأحzab", meaning: "Golongan", verses: 73, type: "Madaniyah", juz: 21 },
  { number: 34, name: "Saba'", arabic: "سبأ", meaning: "Saba'", verses: 54, type: "Makkiyah", juz: 22 },
  { number: 35, name: "Fatir", arabic: "فاطر", meaning: "Pencipta", verses: 45, type: "Makkiyah", juz: 22 },
  { number: 36, name: "Yasin", arabic: "يس", meaning: "Yasin", verses: 83, type: "Makkiyah", juz: 22 },
  { number: 37, name: "As-Saffat", arabic: "الصافات", meaning: "Berbaris", verses: 182, type: "Makkiyah", juz: 23 },
  { number: 38, name: "Sad", arabic: "ص", meaning: "Sad", verses: 88, type: "Makkiyah", juz: 23 },
  { number: 39, name: "Az-Zumar", arabic: "الزمر", meaning: "Rombongan", verses: 75, type: "Makkiyah", juz: 23 },
  { number: 40, name: "Ghafir", arabic: "غافر", meaning: "Pengampun", verses: 85, type: "Makkiyah", juz: 24 },
  { number: 41, name: "Fussilat", arabic: "فصلت", meaning: "Yang Dijelaskan", verses: 54, type: "Makkiyah", juz: 24 },
  { number: 42, name: "Asy-Syura", arabic: "الشورى", meaning: "Musyawarah", verses: 53, type: "Makkiyah", juz: 25 },
  { number: 43, name: "Az-Zukhruf", arabic: "الزخرف", meaning: "Perhiasan", verses: 89, type: "Makkiyah", juz: 25 },
  { number: 44, name: "Ad-Dukhan", arabic: "الدخان", meaning: "Kabut", verses: 59, type: "Makkiyah", juz: 25 },
  { number: 45, name: "Al-Jasiyah", arabic: "الجاثية", meaning: "Berlutut", verses: 37, type: "Makkiyah", juz: 25 },
  { number: 46, name: "Al-Ahqaf", arabic: "الأحقاف", meaning: "Bukit Pasir", verses: 35, type: "Makkiyah", juz: 26 },
  { number: 47, name: "Muhammad", arabic: "محمد", meaning: "Nabi Muhammad", verses: 38, type: "Madaniyah", juz: 26 },
  { number: 48, name: "Al-Fath", arabic: "الفتح", meaning: "Kemenangan", verses: 29, type: "Madaniyah", juz: 26 },
  { number: 49, name: "Al-Hujurat", arabic: "الحجرات", meaning: "Kamar-kamar", verses: 18, type: "Madaniyah", juz: 26 },
  { number: 50, name: "Qaf", arabic: "ق", meaning: "Qaf", verses: 45, type: "Makkiyah", juz: 26 },
  { number: 51, name: "Az-Zariyat", arabic: "الذاريات", meaning: "Angin Menerbangkan", verses: 60, type: "Makkiyah", juz: 26 },
  { number: 52, name: "At-Tur", arabic: "الطور", meaning: "Bukit", verses: 49, type: "Makkiyah", juz: 27 },
  { number: 53, name: "An-Najm", arabic: "النجم", meaning: "Bintang", verses: 62, type: "Makkiyah", juz: 27 },
  { number: 54, name: "Al-Qamar", arabic: "القمر", meaning: "Bulan", verses: 55, type: "Makkiyah", juz: 27 },
  { number: 55, name: "Ar-Rahman", arabic: "الرحمن", meaning: "Maha Pengasih", verses: 78, type: "Madaniyah", juz: 27 },
  { number: 56, name: "Al-Waqi'ah", arabic: "الواقعة", meaning: "Hari Kiamat", verses: 96, type: "Makkiyah", juz: 27 },
  { number: 57, name: "Al-Hadid", arabic: "الحديد", meaning: "Besi", verses: 29, type: "Madaniyah", juz: 27 },
  { number: 58, name: "Al-Mujadalah", arabic: "المجادلة", meaning: "Wanita Penggugat", verses: 22, type: "Madaniyah", juz: 28 },
  { number: 59, name: "Al-Hasyr", arabic: "الحشر", meaning: "Pengusiran", verses: 24, type: "Madaniyah", juz: 28 },
  { number: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", meaning: "Wanita Diuji", verses: 13, type: "Madaniyah", juz: 28 },
  { number: 61, name: "As-Saff", arabic: "الصف", meaning: "Barisan", verses: 14, type: "Madaniyah", juz: 28 },
  { number: 62, name: "Al-Jumu'ah", arabic: "الجمعة", meaning: "Hari Jum'at", verses: 11, type: "Madaniyah", juz: 28 },
  { number: 63, name: "Al-Munafiqun", arabic: "المنافقون", meaning: "Orang Munafik", verses: 11, type: "Madaniyah", juz: 28 },
  { number: 64, name: "At-Tagabun", arabic: "التغابن", meaning: "Hari Dinampakkan", verses: 18, type: "Madaniyah", juz: 28 },
  { number: 65, name: "At-Talaq", arabic: "الطلاق", meaning: "Talak", verses: 12, type: "Madaniyah", juz: 28 },
  { number: 66, name: "At-Tahrim", arabic: "التحريم", meaning: "Pengharaman", verses: 12, type: "Madaniyah", juz: 28 },
  { number: 67, name: "Al-Mulk", arabic: "الملك", meaning: "Kerajaan", verses: 30, type: "Makkiyah", juz: 29 },
  { number: 68, name: "Al-Qalam", arabic: "القلم", meaning: "Pena", verses: 52, type: "Makkiyah", juz: 29 },
  { number: 69, name: "Al-Haqqah", arabic: "الحاقة", meaning: "Hari Kiamat", verses: 52, type: "Makkiyah", juz: 29 },
  { number: 70, name: "Al-Ma'arij", arabic: "المعارج", meaning: "Tempat Naik", verses: 44, type: "Makkiyah", juz: 29 },
  { number: 71, name: "Nuh", arabic: "نوح", meaning: "Nabi Nuh", verses: 28, type: "Makkiyah", juz: 29 },
  { number: 72, name: "Al-Jinn", arabic: "الجن", meaning: "Jin", verses: 28, type: "Makkiyah", juz: 29 },
  { number: 73, name: "Al-Muzzammil", arabic: "المزمل", meaning: "Berselimut", verses: 20, type: "Makkiyah", juz: 29 },
  { number: 74, name: "Al-Muddassir", arabic: "المدثر", meaning: "Berselubung", verses: 56, type: "Makkiyah", juz: 29 },
  { number: 75, name: "Al-Qiyamah", arabic: "القيامة", meaning: "Kiamat", verses: 40, type: "Makkiyah", juz: 29 },
  { number: 76, name: "Al-Insan", arabic: "الإنسان", meaning: "Manusia", verses: 31, type: "Madaniyah", juz: 29 },
  { number: 77, name: "Al-Mursalat", arabic: "المرسلات", meaning: "Malaikat Diutus", verses: 50, type: "Makkiyah", juz: 29 },
  { number: 78, name: "An-Naba'", arabic: "النبأ", meaning: "Berita Besar", verses: 40, type: "Makkiyah", juz: 30 },
  { number: 79, name: "An-Nazi'at", arabic: "النازعات", meaning: "Malaikat Pencabut", verses: 46, type: "Makkiyah", juz: 30 },
  { number: 80, name: "'Abasa", arabic: "عبس", meaning: "Bermuka Masam", verses: 42, type: "Makkiyah", juz: 30 },
  { number: 81, name: "At-Takwir", arabic: "التكوير", meaning: "Menggulung", verses: 29, type: "Makkiyah", juz: 30 },
  { number: 82, name: "Al-Infitar", arabic: "الانفطار", meaning: "Terbelah", verses: 19, type: "Makkiyah", juz: 30 },
  { number: 83, name: "Al-Mutaffifin", arabic: "المطففين", meaning: "Orang Curang", verses: 36, type: "Makkiyah", juz: 30 },
  { number: 84, name: "Al-Insyiqaq", arabic: "الانشقاق", meaning: "Terbelah", verses: 25, type: "Makkiyah", juz: 30 },
  { number: 85, name: "Al-Buruj", arabic: "البروج", meaning: "Gugusan Bintang", verses: 22, type: "Makkiyah", juz: 30 },
  { number: 86, name: "At-Tariq", arabic: "الطارق", meaning: "Yang Datang Malam", verses: 17, type: "Makkiyah", juz: 30 },
  { number: 87, name: "Al-A'la", arabic: "الأعلى", meaning: "Yang Maha Tinggi", verses: 19, type: "Makkiyah", juz: 30 },
  { number: 88, name: "Al-Gasyiyah", arabic: "الغاشية", meaning: "Hari Pembalasan", verses: 26, type: "Makkiyah", juz: 30 },
  { number: 89, name: "Al-Fajr", arabic: "الفجر", meaning: "Fajar", verses: 30, type: "Makkiyah", juz: 30 },
  { number: 90, name: "Al-Balad", arabic: "البلد", meaning: "Negeri", verses: 20, type: "Makkiyah", juz: 30 },
  { number: 91, name: "Asy-Syams", arabic: "الشمس", meaning: "Matahari", verses: 15, type: "Makkiyah", juz: 30 },
  { number: 92, name: "Al-Lail", arabic: "الليل", meaning: "Malam", verses: 21, type: "Makkiyah", juz: 30 },
  { number: 93, name: "Ad-Duha", arabic: "الضحى", meaning: "Waktu Duha", verses: 11, type: "Makkiyah", juz: 30 },
  { number: 94, name: "Asy-Syarh", arabic: "الشرح", meaning: "Melapangkan", verses: 8, type: "Makkiyah", juz: 30 },
  { number: 95, name: "At-Tin", arabic: "التين", meaning: "Buah Tin", verses: 8, type: "Makkiyah", juz: 30 },
  { number: 96, name: "Al-'Alaq", arabic: "العلق", meaning: "Segumpal Darah", verses: 19, type: "Makkiyah", juz: 30 },
  { number: 97, name: "Al-Qadr", arabic: "القدر", meaning: "Kemuliaan", verses: 5, type: "Makkiyah", juz: 30 },
  { number: 98, name: "Al-Bayyinah", arabic: "البينة", meaning: "Bukti Nyata", verses: 8, type: "Madaniyah", juz: 30 },
  { number: 99, name: "Az-Zalzalah", arabic: "الزلزلة", meaning: "Guncangan", verses: 8, type: "Madaniyah", juz: 30 },
  { number: 100, name: "Al-'Adiyat", arabic: "العاديات", meaning: "Berlari Kencang", verses: 11, type: "Makkiyah", juz: 30 },
  { number: 101, name: "Al-Qari'ah", arabic: "القارعة", meaning: "Hari Kiamat", verses: 11, type: "Makkiyah", juz: 30 },
  { number: 102, name: "At-Takasur", arabic: "التكاثر", meaning: "Bermegah-megahan", verses: 8, type: "Makkiyah", juz: 30 },
  { number: 103, name: "Al-'Asr", arabic: "العصر", meaning: "Masa", verses: 3, type: "Makkiyah", juz: 30 },
  { number: 104, name: "Al-Humazah", arabic: "الهمزة", meaning: "Pengumpat", verses: 9, type: "Makkiyah", juz: 30 },
  { number: 105, name: "Al-Fil", arabic: "الفيل", meaning: "Gajah", verses: 5, type: "Makkiyah", juz: 30 },
  { number: 106, name: "Quraisy", arabic: "قريش", meaning: "Suku Quraisy", verses: 4, type: "Makkiyah", juz: 30 },
  { number: 107, name: "Al-Ma'un", arabic: "الماعون", meaning: "Barang Berguna", verses: 7, type: "Makkiyah", juz: 30 },
  { number: 108, name: "Al-Kausar", arabic: "الكوثر", meaning: "Nikmat Berlimpah", verses: 3, type: "Makkiyah", juz: 30 },
  { number: 109, name: "Al-Kafirun", arabic: "الكافرون", meaning: "Orang Kafir", verses: 6, type: "Makkiyah", juz: 30 },
  { number: 110, name: "An-Nasr", arabic: "النصر", meaning: "Pertolongan", verses: 3, type: "Madaniyah", juz: 30 },
  { number: 111, name: "Al-Lahab", arabic: "المسد", meaning: "Gejolak Api", verses: 5, type: "Makkiyah", juz: 30 },
  { number: 112, name: "Al-Ikhlas", arabic: "الإخلاص", meaning: "Ikhlas", verses: 4, type: "Makkiyah", juz: 30 },
  { number: 113, name: "Al-Falaq", arabic: "الفلق", meaning: "Waktu Subuh", verses: 5, type: "Makkiyah", juz: 30 },
  { number: 114, name: "An-Nas", arabic: "الناس", meaning: "Manusia", verses: 6, type: "Makkiyah", juz: 30 }
];
